version: '3.7'
services:
  api_gateway:
    hostname: api_gateway
    image: nginx_gateway_image:latest
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: api_gateway-sd
    ports:
      - protocol: tcp
        target: 80
        published: 8881
    environment:
      NGINX_PORT: 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lab-co
    depends_on:
      - pod1
      - pod2
  pod1:
    hostname: pod1
    container_name: pod1
    build:
      context: .
      dockerfile: Dockerfile
    image: pod1
    volumes:
      - ./:/app
    networks:
      - lab-co
    env_file:
      - ./.env

  pod2:
    hostname: pod2
    container_name: pod2
    build:
      context: .
      dockerfile: Dockerfile
    image: pod2
    volumes:
      - ./:/app
    networks:
      - lab-co
    env_file:
      - ./.env
  db:
    image: mysql:8
    container_name: lab-so_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
    tty: true
    volumes:
      - db_lab-co:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lab-co
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - lab-co
    depends_on:
      - db

networks:
  lab-co:
    driver: bridge
volumes:
  db_lab-co:
    driver: local