version: '3.7'
services:
  db:
    image: mysql:8
    container_name: lab-so_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
    tty: true
    volumes:
      - db_lab-co:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lab-co
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - lab-co
    depends_on:
      - db

networks:
  lab-co:
    driver: bridge
volumes:
  db_lab-co:
    driver: local